platform :ios, '8.0'
use_frameworks!

target 'UCLA Radio' do
  pod 'Alamofire', '~> 3.4'
  pod 'ASHorizontalScrollView', '~> 1.1'
  pod 'SDWebImage', '~>3.7'
  pod "KRLCollectionViewGridLayout", "~> 0.4.1"
  
  # potentially useful for schedule
  # pod 'HTHorizontalSelectionList', '~> 0.7.0'
end
